import type { Metadata } from "next";
import { Quicksand, Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Toaster } from "sonner";

import AppLayout from "@/components/AppLayout";
import Script from "next/script";

const quickSand = Quicksand({
  weight: ["300", "400", "600"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-quicksand",
});

const popins = Poppins({
  weight: ["500", "400", "600"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Razorpay Checkout.js must be in the head before anything interactive */}
        <Script
          src="https://checkout.razorpay.com/v1/checkout.js"
          strategy="beforeInteractive"
        
        />
      </head>
      <body className={`${quickSand.variable} ${popins.variable} antialiased`}>
        <Providers>
          <AppLayout>{children}</AppLayout>
          <Toaster position="top-right" />
        </Providers>
      </body>
    </html>
  );
}
