import type { Metadata } from "next";
import { Geist, Geist_Mono, Quicksand, Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Toaster } from "sonner";
import Navbar from "@/components/Navbar";
import AppLayout from "@/components/AppLayout";

const quickSand = Quicksand({
  weight: ["300", "400", "600"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-quicksand",
});

const popins = Poppins({
  weight: ["500", "400", "600"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quickSand.variable} ${popins.variable} antialiased`}>
        <Providers>
          <AppLayout>{children}</AppLayout>
          <Toaster position="top-right" />
        </Providers>
      </body>
    </html>
  );
}
