import type { Metadata } from "next";
import { Geist, Geist_Mono, Quicksand, Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Toaster } from "sonner";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const quickSand = Quicksand({
  weight: ["300", "400", "600"],
  style: ["normal"],
  subsets: ["latin"],
});

const popins = Poppins({
  weight: ["500", "400", "600"],
  style: ["normal"],
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Navbar/>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${quickSand.className} ${popins.className} antialiased`}
      >
          <Providers>{children}</Providers>
            <Toaster position="top-right" />
      </body>
    </html>
  );
}
